apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-commander
spec:
  releaseName: redis-commander
  values:
    image:
      repository: ghcr.io/joeferner/redis-commander
      tag: latest
    connections:
      local_production_json: >-
        {
          "noSave": false,
          "noLogData": false,
          "ui": {
            "sidebarWidth": 250,
            "locked": false,
            "cliHeight": 320,
            "cliOpen": false,
            "foldingChar": ":",
            "jsonViewAsDefault": "none",
            "binaryAsHex": true,
            "maxHashFieldSize": 0
          },
          "redis": {
            "readOnly": false,
            "flushOnImport": false,
            "useScan": true,
            "scanCount": 100,
            "rootPattern": "*",
            "connectionName": "redis-commander",
            "defaultLabel": "local",
            "defaultSentinelGroup": "mymaster"
          },
          "server": {
            "address": "0.0.0.0",
            "port": 8081,
            "urlPrefix": "",
            "signinPath": "signin",
            "httpAuthHeaderName": "Authorization",
            "trustProxy": false,
            "clientMaxBodySize": "100kb",
            "httpAuth": {
              "username": "",
              "password": "",
              "passwordHash": "",
              "comment": "to enable http auth set username and either password or passwordHash",
              "jwtSecret": ""
            }
          },
          "sso": {
            "enabled": false,
            "jwtSharedSecret": "",
            "jwtAlgorithms": ["HS256", "HS384", "HS512"],
            "allowedIssuer": "",
            "audience": "",
            "subject": ""
          },
          "connections": [
            {
              "label": "redis-sentinel-service-x",
              "sentinels": "19.94.12.11:26379",
              "sentinelName": "mymaster",
              "dbIndex": 0
            },
            {
              "label": "redis-sentinel-service-y",
              "sentinels": "19.94.12.11:26379",
              "sentinelName": "mymaster",
              "dbIndex": 0
            },
            {
              "label": "redis-server-service-xz",
              "host": "19.94.12.11",
              "port": "6379",
              "dbIndex": 0
            },
            {
              "label": "redis-server-service-yz",
              "host": "19.94.12.11",
              "port": "6379",
              "dbIndex": 0
            }
          ]
        }
    volumeMounts:
      - name: local-production
        mountPath: /redis-commander/config
    volumes:
        - name: local-production
          configMap:
            name: redis-commander-configmap
  rollback:
    disableWait: true
    cleanupOnFail: true
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  maxHistory: 5
